### ISSUE TITLE
Question on reference documentation

### ISSUE THREAD

**Issue by hmaurer** [Skinz3/Legends#1]
Hello!

I just stumbled upon your project and it seems very interesting. I have a quick question: how did you figure out the protocol? Did you fully reverse-engineer it by sniffing the communications, or is there a less tedious way?

Thanks!
H.

**Comment by moonshadow565** [comment]
Most of the work has been done in:
https://github.com/LeagueSandbox/GameServer/
Which in turn is direct port(copy paste) from even older project called Intwars

**Comment by Skinz3** [comment]
Legends.Protocol.GameClient is based on league sandbox https://github.com/LeagueSandbox/GameServer/ , I tried to improve it, and to change unk variables.
