### ISSUE TITLE
get compile error ,CSC : error CS2001

### ISSUE THREAD

**Issue by perfectplug** [Skinz3/Legends#3]
1>  CSC : error CS2001: Source file 'Z:\LeagueSandbox\Legends\Sources\Fantome.League\IO\BIN\BINFileStructure.cs' could not be found.
1>  CSC : error CS2001: Source file 'Z:\LeagueSandbox\Legends\Sources\Fantome.League\IO\BIN\BINFileValue.cs' could not be found.
1>  CSC : error CS2001: Source file 'Z:\LeagueSandbox\Legends\Sources\Fantome.League\IO\BIN\BINFileValuePair.cs' could not be found.
1>  CSC : error CS2001: Source file 'Z:\LeagueSandbox\Legends\Sources\Fantome.League\IO\BIN\IBINFileValue.cs' could not be found.
1>  CSC : error CS2001: Source file 'Z:\LeagueSandbox\Legends\Sources\Fantome.League\IO\BIN\BINFile.cs' could not be found.
1>  CSC : error CS2001: Source file 'Z:\LeagueSandbox\Legends\Sources\Fantome.League\IO\BIN\BINFileAdditionalData.cs' could not be found.
1>  CSC : error CS2001: Source file 'Z:\LeagueSandbox\Legends\Sources\Fantome.League\IO\BIN\BINFileContainer.cs' could not be found.
1>  CSC : error CS2001: Source file 'Z:\LeagueSandbox\Legends\Sources\Fantome.League\IO\BIN\BINFileEntry.cs' could not be found.
1>  CSC : error CS2001: Source file 'Z:\LeagueSandbox\Legends\Sources\Fantome.League\IO\BIN\BINFileMap.cs' could not be found.
1>  CSC : error CS2001: Source file 'Z:\LeagueSandbox\Legends\Sources\Fantome.League\IO\OBJ\OBJFace.cs' could not be found.
1>  CSC : error CS2001: Source file 'Z:\LeagueSandbox\Legends\Sources\Fantome.League\IO\OBJ\OBJFile.cs' could not be found.

I found no these files?
 Can you upload these files?

**Comment by perfectplug** [comment]
solve this problem.
the original project
https://github.com/LoL-Fantome/Fantome.Libraries.League

**Comment by Skinz3** [comment]
Sorry for late reply. This project has no dependency with Fantom League library, you can just remove the reference.
